name: Cakepediaa
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.20
 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2 # Pastikan untuk menggunakan versi terbaru

flutter:
  uses-material-design: true

  assets:
    - assets/images/kue1.jpg
    - assets/images/kue2.jpg
    - assets/images/kue3.jpg
    - assets/images/kue4.jpg
    - assets/images/kue5.jpg
    - assets/images/kue6.jpg
    - assets/images/logo.png
    - assets/images/chocolate1.jpg
    - assets/images/chocolate2.jpg
    - assets/images/chocolate3.jpg
    - assets/images/strawberry1.jpg
    - assets/images/strawberry2.jpg
    - assets/images/strawberry3.jpg
    - assets/images/matcha1.jpg
    - assets/images/matcha2.jpg
    - assets/images/matcha3.jpg
    - assets/images/cream1.jpg
    - assets/images/cream2.jpg
    - assets/images/cream3.jpg
    - assets/images/almond1.jpg
    - assets/images/almond2.jpg
    - assets/images/almond3.jpg
    - assets/images/lemon1.jpg
    - assets/images/lemon2.jpg
    - assets/images/lemon3.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png" # Ganti dengan path ke ikon Anda